import { PlanData } from './plan-types';

export const defaultPlanData: PlanData = {
  title: "Liz's 2026 Life Plan",
  subtitle: "Started March 15, 2026 · Target: December 31, 2026",
  tagline: "Ten goals. A real deadline. A plan built around what's actually true.",
  alert: {
    title: "The CCBB Clock Is Ticking — This Changes Everything",
    body: "The CCBB contract expires in September 2026 — that's 6 months away. Right now, CCBB is contributing roughly $4,300–5,300/month to Wildflower's revenue. When it drops off, you go from ~$7–8k/month back to $2,715/month unless you've built your pipeline. You need to use this window — while CCBB money is still coming in — to aggressively acquire new clients. Wildflower client acquisition is Priority #1, starting now."
  },
  realityCards: [
    { id: 'rc1', label: 'Wildflower Revenue (ex-CCBB)', current: '$2,715/mo', goal: 'Goal: $10,000/mo', gap: 'Gap: $7,285/mo → ~5 new mgmt clients' },
    { id: 'rc2', label: 'Your W2 Take-Home', current: '~$2,500–2,700/mo', goal: 'Goal: $10,000/mo post-tax', gap: 'Gap: ~$7,300–7,500/mo personal income' },
    { id: 'rc3', label: 'Weight', current: '155.3 lbs', goal: 'Goal: 135 lbs', gap: 'Gap: 20.3 lbs → ~2.5 lbs/month' },
    { id: 'rc4', label: 'Down Payment Saved', current: '$20,000', goal: 'Target: $44K for 20% down on $220K home', gap: "Need $24K more · $220K @ 20% down ≈ $1,400–1,500/mo all-in" },
    { id: 'rc5', label: 'IG Followers', current: 'Personal: 2,633', goal: 'Wildflower: 831', gap: 'Personal brand needs revitalizing — it\'s also your best Wildflower marketing' },
    { id: 'rc6', label: 'CCBB Revenue At Risk', current: '$4,300–5,300/mo', goal: 'Replaced by new clients', gap: 'Drops off: September 2026' },
  ],
  funnelSteps: [
    { price: '$297', name: 'Deep Dive Session', type: 'Entry point' },
    { price: '$550', name: 'Social Media Audit', type: 'Diagnose the problem' },
    { price: '$2,500', name: 'Social Media Strategy', type: 'Build the roadmap' },
  ],
  funnelTiers: [
    { badge: 'Group', price: '$350/mo', name: 'Group Consulting', desc: 'Implement the strategy with group guidance & accountability. Scalable — you can serve 15–20 clients in one container.', tag: '🎯 April 22 webinar offer', style: 'group' },
    { badge: '1:1', price: '$750/mo', name: '1:1 Consulting', desc: 'Personalized ongoing support following the strategy. Higher access to Liz. Mid-tier between group and full management.', tag: '⏱ ~2–4 hrs/month per client', style: 'one' },
    { badge: 'Done-For-You', price: '$1,500/mo', name: 'Social Media Management', desc: 'Fully done-for-you execution via VAs. Liz oversees strategy only. Scalable — no longer capped by your personal time.', tag: '🤝 VA-led · Liz holds strategy', style: 'mgmt' },
  ],
  funnelNote: "This model removes the ceiling that was always in the old version. Management is no longer capped by your hours — the VAs handle execution, you handle strategy and client relationships. Group consulting is where you scale volume without adding proportional time. Your personal brand IS your Wildflower marketing — when you show up consistently, leads enter every tier of this funnel.",
  mathTable: {
    header: "How to hit $10,000/month in Wildflower revenue — sample mix using the new model:",
    columns: ['Service', 'Price', 'Target # clients', 'Monthly revenue'],
    rows: [
      { cells: ['Group Consulting Program', '$350/mo', '10–15 clients', '$3,500–5,250'] },
      { cells: ['1:1 Ongoing Consulting', '$750/mo', '4–5 clients', '$3,000–3,750'] },
      { cells: ['Social Media Management (VA-led)', '$1,500/mo gross', '2–3 clients', '$3,000–4,500 gross*'] },
      { cells: ['Strategy Packages', '$2,500 one-time', '1–2/mo', '$2,500–5,000 cash flow'] },
      { cells: ['Audits + Deep Dives', '$297–$550', '2–3/mo', 'Pipeline fuel — converts to recurring'] },
      { cells: ['Target mix by Sept 2026', '~10 group + 4 one-on-one + 2 management', '', '~$10,000+/mo'], highlight: true },
      { cells: ['⚠️ CCBB drops off Sept 2026', '~$4,300–5,300/month disappears. Must be replaced — and with this model, it\'s very achievable.', '', ''], warning: true },
    ],
    note: "*Management revenue is gross — VA costs come out of this. But with VAs executing, you can hold more management clients than before without hitting a time wall. The real scale play is the group program: 15 clients in one container takes the same time as 3. The bottleneck is still leads — the model is right, the pipeline is the work."
  },
  networkContacts: [
    { name: 'The Connective', sub: 'B2B Networking · Fully Remote', desc: "This is your most direct source of Wildflower clients. Every member is a business owner who could need social media management. Show up consistently, introduce Wildflower clearly, follow up with every new connection. Don't just attend — build relationships that convert." },
    { name: 'OUT Georgia', sub: 'GA LGBTQ+ Chamber of Commerce', desc: "A community of business owners who value supporting each other — high trust environment for referrals. Attend events, be visible as Wildflower, and ask members directly if they know anyone who needs social media help. Referrals from here will close faster than cold outreach." },
    { name: 'My Personal Network', sub: 'Accountability Group · Daily Check-ins', desc: "Your daily structure and accountability backbone. Part 4 (post for your business daily) directly supports your Wildflower marketing and personal brand. Part 6 (log + text the group) keeps you honest. These 6 parts, done consistently, will compound over 9 months." },
  ],
  incomeTable: {
    header: "Wildflower money is not Liz money — here's how both goals get met",
    sub: "As your S-Corp grows, you can increase your W2 salary AND take owner distributions (which aren't subject to self-employment tax). Combined with your outside income streams, $10k/month post-tax is achievable.",
    columns: ['Income Source', 'Today', 'By End of 2026 (target)'],
    rows: [
      { cells: ['Wildflower W2 salary (gross)', '$3,000/mo', '$5,500–6,000/mo'] },
      { cells: ['Wildflower S-Corp distributions', '$0', '$1,500–2,000/mo'] },
      { cells: ['Coffee & Cavaliers POD', '$0', '$1,000–1,500/mo'] },
      { cells: ['Personal Brand', '$0', '$1,000–2,000/mo'] },
      { cells: ['Redford UGC', '$0', '$500–1,000/mo'] },
      { cells: ['Total Post-Tax (est.)', '~$2,500–2,700/mo', '~$9,500–11,000/mo'], total: true },
    ]
  },
  mortgage: {
    title: '🏡 Home Purchase — Where Things Stand',
    cards: [
      { label: 'Down Payment Saved', value: '$20,000', note: 'Need $44K total — $24K more to go' },
      { label: 'Target Home Price', value: '$220,000', note: '20% down = $44K · loan = $176K' },
      { label: 'Est. Monthly Payment', value: '~$1,400–1,500/mo', note: '$176K @ 7%, 30yr + taxes/insurance · no PMI' },
    ],
    body: "The plan: $220K home, 20% down ($44K), conventional 30-year loan. At 7%, your principal + interest on $176K is ~$1,170/month — add taxes and insurance and you land right at $1,400–1,500/month with no PMI and no FHA. You have $20K saved, so you need $24K more. At $2,000–2,500/month in savings (achievable once Wildflower is scaling), you're there in 10–12 months. The two things that need to happen in parallel: save to $44K, and build documented consistent income so you qualify independently — or have a strong cosigner in place. Every new Wildflower client and every W2 increase you take on record moves both needles."
  },
  phases: [
    {
      id: 'phase1',
      number: 1,
      title: 'Sell, Launch & Build Pipeline',
      dates: 'March – May 2026 · ~3 months',
      focus: 'Urgency: HIGH · CCBB expires in 6 months',
      colorClass: 'olive',
      intro: "You don't have the luxury of a slow ramp. CCBB is gone in September. The single most important thing you can do right now is sell Wildflower services aggressively while the CCBB revenue is still covering your baseline. The root problem is marketing — you're great at this for clients but not doing it for yourself. That changes now. The April 22 webinar is your first major lead gen event, and everything before it should point toward it.",
      webinarCallout: {
        date: 'APR\n22',
        title: '🎯 Webinar — Your First Big Pipeline Opportunity',
        body: "The April 22 webinar is more than a content event — it's a lead generation engine. Every person who shows up is a potential audit, strategy, or management client. Treat it that way.",
        bullets: [
          'Promote it heavily from now until April 22 — IG, email, DMs, everywhere',
          'Closing offer: the Social Media Audit at $550 — pitch it at the end with a webinar-exclusive window.',
          'Follow up with every single attendee within 24 hours',
          'Goal: convert 3–5 webinar attendees into audits → those become consulting clients'
        ]
      },
      actionGroups: [
        { id: 'p1-wf-setup', icon: '🌸', title: 'Wildflower — One-Time Setup', items: [
          { id: 'p1ws1', text: 'Create referral partner one-sheeter: who is your ideal client, what problem you solve, and how to make an introduction', type: 'normal', checked: false },
          { id: 'p1ws2', text: 'Go back through your calendar and manually add any 1-on-1 contacts from the last 90 days into GHL', type: 'normal', checked: false },
          { id: 'p1ws3', text: 'Build a referral partner pipeline in GHL with stages: Met → Followed Up → Referred Someone → Closed', type: 'normal', checked: false },
          { id: 'p1ws4', text: 'Set up 2-step GHL follow-up sequence: Day 3 — thank you + one-sheeter attached; Day 21 — check-in message', type: 'normal', checked: false },
          { id: 'p1ws5', text: 'Finish website contact form fields and get embed code from GHL (name, email, business name, service interest, short description, how did you hear about us)', type: 'normal', checked: false },
          { id: 'p1ws6', text: 'Build GHL nurture sequence for website form submissions (separate from referral partner sequence)', type: 'normal', checked: false },
          { id: 'p1ws7', text: 'Update website copy to reflect current services once form is ready', type: 'normal', checked: false },
        ]},
        { id: 'p1-wf-webinar', icon: '🎯', title: 'Wildflower — Webinar Push (Apr 22)', items: [
          { id: 'p1wv1', text: 'Week of Mar 23: Post 2x about webinar on personal IG; DM 10–15 warm contacts personally inviting them; share to Wildflower IG', type: 'urgent', checked: false },
          { id: 'p1wv2', text: 'Week of Mar 31: Send email #2 to list — lead with what they\'ll learn (the 4 Ps), one clear CTA; promote webinar 3x on social', type: 'urgent', checked: false },
          { id: 'p1wv3', text: 'Week of Apr 6: Email registered attendees a reminder; push registration on stories and feed; send email #3 to list', type: 'urgent', checked: false },
          { id: 'p1wv4', text: 'Week of Apr 13: Stories every day counting down; send final reminder email; have $550 audit sales page and 48–72hr exclusive window ready', type: 'urgent', checked: false },
          { id: 'p1wv5', text: 'Apr 22: Run webinar; close with $550 audit offer; follow up with every attendee within 24 hours; send replay + offer to no-shows', type: 'urgent', checked: false },
          { id: 'p1wv6', text: 'Week of Apr 27: Follow up all warm leads from webinar; onboard new clients; repurpose webinar into 3–5 posts (Team)', type: 'normal', checked: false },
        ]},
        { id: 'p1-cc-setup', icon: '☕', title: 'Coffee & Cavaliers — One-Time Setup', items: [
          { id: 'p1cs1', text: 'Finalize brand identity: color palette, logo/wordmark, tone of voice', type: 'normal', checked: false },
          { id: 'p1cs2', text: 'Choose platform: Etsy first (lower barrier, built-in traffic)', type: 'normal', checked: false },
          { id: 'p1cs3', text: 'Set up Printify or Printful account and connect to Etsy store', type: 'normal', checked: false },
          { id: 'p1cs4', text: 'Design first 10–15 products (mugs, t-shirts, tote bags — Cavalier + coffee themes)', type: 'normal', checked: false },
          { id: 'p1cs5', text: 'Write SEO-optimized titles and descriptions for all product listings', type: 'normal', checked: false },
          { id: 'p1cs6', text: 'Create C&C Instagram account', type: 'normal', checked: false },
          { id: 'p1cs7', text: 'Create C&C TikTok account', type: 'normal', checked: false },
          { id: 'p1cs8', text: 'Write bios for both C&C accounts', type: 'normal', checked: false },
          { id: 'p1cs9', text: 'Launch store publicly — announce on personal IG, Wildflower IG, and Redford accounts', type: 'normal', checked: false },
          { id: 'p1cs10', text: 'Create a content strategy doc for C&C: content pillars, post types, batch topics', type: 'normal', checked: false },
        ]},
        { id: 'p1-rf-setup', icon: '🐾', title: 'Redford — One-Time Setup', items: [
          { id: 'p1rs1', text: 'Create dedicated Redford Instagram account', type: 'normal', checked: false },
          { id: 'p1rs2', text: 'Create dedicated Redford TikTok account', type: 'normal', checked: false },
          { id: 'p1rs3', text: 'Write bios for both Redford accounts (clear niche, personality)', type: 'normal', checked: false },
          { id: 'p1rs4', text: 'Define content pillars: day-in-the-life, product reviews, C&C crossover, funny/relatable Cavalier moments', type: 'normal', checked: false },
          { id: 'p1rs5', text: 'Start media kit document in Canva (basic version — update as numbers grow)', type: 'normal', checked: false },
          { id: 'p1rs6', text: 'Create a content strategy doc for Redford', type: 'normal', checked: false },
        ]},
        { id: 'p1-pb-setup', icon: '📱', title: 'Personal Brand — One-Time Setup', items: [
          { id: 'p1ps1', text: 'Update @lizannbach IG bio: clear statement of what you do and who you help ("I help small businesses stop guessing on social media")', type: 'normal', checked: false },
          { id: 'p1ps2', text: 'Write down your 3 content pillars: (1) social media education — tips, frameworks, myth-busting; (2) behind-the-scenes of Wildflower; (3) life/lifestyle — personality, Redford, coffee, honest moments', type: 'normal', checked: false },
          { id: 'p1ps3', text: 'Create a simple lead magnet (one-page freebie related to the 4 Ps or content planning — something you can make in an hour)', type: 'normal', checked: false },
          { id: 'p1ps4', text: 'Add lead magnet link to Smartlink bio alongside webinar link', type: 'normal', checked: false },
        ]},
        { id: 'p1-hl-setup', icon: '⚖️', title: 'Health — One-Time Setup', items: [
          { id: 'p1hs1', text: 'Choose ONE food tracking method and commit to it for 30 days (MyFitnessPal, Lose It, paper journal, or meal photos — consistency matters more than method)', type: 'normal', checked: false },
          { id: 'p1hs2', text: 'Block 3 movement sessions per week in your calendar — treat like client appointments', type: 'normal', checked: false },
          { id: 'p1hs3', text: 'Name what "movement" looks like for you specifically (walk, gym, class — write it down so it\'s real)', type: 'normal', checked: false },
          { id: 'p1hs4', text: 'Set a monthly weigh-in date (same day, same time, same conditions — no daily scale)', type: 'normal', checked: false },
        ]},
        { id: 'p1-hm-setup', icon: '🏡', title: 'Home — One-Time Setup', items: [
          { id: 'p1hm1', text: 'Prep all jewelry pieces for Sunday Mar 29 photo shoot — clean, organize, and group by style', type: 'urgent', checked: false },
          { id: 'p1hm2', text: 'Walk every room and categorize everything: Keep / Sell / Donate / Discard', type: 'normal', checked: false },
          { id: 'p1hm3', text: 'Do a full inventory of all jewelry stock', type: 'normal', checked: false },
          { id: 'p1hm4', text: 'List all jewelry on at least 2 platforms: Depop, Etsy, and/or Facebook Marketplace', type: 'normal', checked: false },
          { id: 'p1hm5', text: 'Choose one donation drop-off location so bags don\'t pile up', type: 'normal', checked: false },
          { id: 'p1hm6', text: 'Have a direct conversation with your broker: what income level do you need documented to qualify solo for a ~$220K home? Get a specific number.', type: 'normal', checked: false },
          { id: 'p1hm7', text: 'Ask broker: does increasing your W2 salary help, and by how much? What timeline do they need to see it?', type: 'normal', checked: false },
        ]},
      ],
      milestone: 'Phase 1 milestone (end of May): 3 new Wildflower management clients signed ($4,500/mo added). Home is actively decluttered. Jewelry is listed and selling. C&C is live. Redford has 200+ followers and a content rhythm. Personal brand is posting again. Weight: ~152 lbs.',
      dailyParts: [
        { id: 'dp1', label: 'Part 1 · Within 1 hour of waking', items: [
          { id: 'dp1a', text: 'Drink 20 oz of water', checked: false },
          { id: 'dp1b', text: "Write down the 5 things you're working on today", checked: false },
          { id: 'dp1c', text: 'Write down your plans for all meals and snacks', checked: false },
        ]},
        { id: 'dp2', label: 'Part 2 · Movement', items: [
          { id: 'dp2a', text: 'Walk 5,000 steps', checked: false },
        ]},
        { id: 'dp3', label: 'Part 3 · Mind', items: [
          { id: 'dp3a', text: 'Listen to 20 minutes of educational audio content', checked: false },
        ]},
        { id: 'dp4', label: 'Part 4 · Business Visibility', items: [
          { id: 'dp4a', text: 'Post on social media once for your business (any channel — personal brand, Wildflower, Redford, or C&C all count)', checked: false },
        ]},
        { id: 'dp5', label: 'Part 5 · The Integrity Pause', wide: true, items: [
          { id: 'dp5a', text: 'Before making a decision today, pause and ask: "Would I be comfortable if this decision were publicly known?"', checked: false },
        ]},
        { id: 'dp6', label: 'Part 6 · Close the Day', wide: true, items: [
          { id: 'dp6a', text: 'Log whether you did all parts on your daily checklist', checked: false },
          { id: 'dp6b', text: 'Text the My Personal Network groupchat — all done at once', checked: false },
        ]},
      ],
      dailyAddons: [
        { id: 'da1', icon: '🌸', title: 'Respond to all Wildflower leads & DMs', desc: 'Every inquiry gets a same-day response. Speed to lead wins deals.', checked: false, schedule: 'weekdays' },
        { id: 'da2', icon: '🐾', title: 'One Redford post or story', desc: 'Authentic and consistent beats polished and sporadic. Even a quick photo counts.', checked: false, schedule: 'daily' },
        { id: 'da3', icon: '✨', title: '10-minute tidy', desc: 'Reset one surface or area before bed. This is the clean home built in 10 minutes a day.', checked: false, schedule: 'daily' },
        { id: 'da4', icon: '💬', title: 'Engage with 5–10 accounts in your niche', desc: 'Comment genuinely on ideal client content. Organic reach without ads.', checked: false, schedule: 'weekdays' },
      ],
      weeklyAreas: [
        { id: 'wa-wf', title: '🌸 Wildflower', color: 'bg-olive', items: [
          { id: 'ww1', text: 'Monday: Review your lead pipeline — who needs follow-up this week?', checked: false },
          { id: 'ww2', text: '2x per week: Send 3–5 outreach messages (referral asks, warm DMs, LinkedIn connections)', checked: false },
          { id: 'ww3', text: '1x per week: Publish one Wildflower content piece (tip, case study, result)', checked: false },
          { id: 'ww4', text: 'Weekly: Show up in The Connective — introduce yourself to new members, follow up with existing connections.', checked: false },
          { id: 'ww5', text: 'Monthly: Engage with OUT Georgia — attend events, introduce Wildflower to members, ask for referrals', checked: false },
          { id: 'ww6', text: 'Weekly: Check webinar registrations — are you promoting enough?', checked: false },
          { id: 'ww7', text: 'Friday: Log revenue + pipeline status — on track for 1 new client/month?', checked: false },
        ]},
        { id: 'wa-pb', title: '📱 Personal Brand', color: 'bg-slate', items: [
          { id: 'wp1', text: 'Sunday or Monday: Batch-plan your content for the week — 3 feed posts + daily stories', checked: false },
          { id: 'wp2', text: '3x per week: Publish a feed post (social media tips, behind-the-scenes, life content)', checked: false },
          { id: 'wp3', text: '1x per week: Promote the April 22 webinar directly — link in bio, story countdown, etc.', checked: false },
          { id: 'wp4', text: 'Weekly: Add at least one touchpoint to grow your email list', checked: false },
        ]},
        { id: 'wa-cc', title: '☕ Coffee & Cavaliers', color: 'bg-[hsl(30,15%,41%)]', items: [
          { id: 'wc1', text: 'Weeks 1–4 (March): Finalize brand, set up store, design first 10 products', checked: false },
          { id: 'wc2', text: 'Week 5 (early April): Launch the store publicly', checked: false },
          { id: 'wc3', text: 'Post-launch (weekly): Post 3–4x/week on C&C social', checked: false },
          { id: 'wc4', text: 'Weekly: Check which products are getting saves/clicks — optimize listings', checked: false },
        ]},
      { id: 'wa-red', title: '🐾 Redford — UGC', color: 'bg-[hsl(100,18%,40%)]', items: [
          { id: 'wr1', text: 'Weekly: Create 1–2 new UGC portfolio pieces (product demos, lifestyle shots)', checked: false },
          { id: 'wr2', text: 'Weekly: Pitch 5–10 brands via email/Bento — track responses', checked: false },
          { id: 'wr3', text: 'Weekly: Follow up on all unanswered brand pitches (wait 5–7 days then follow up)', checked: false },
          { id: 'wr4', text: 'Weekly: Engage with pet/lifestyle brand accounts to get on their radar', checked: false },
        ]},
        { id: 'wa-home', title: '🏠 Home', color: 'bg-[hsl(260,10%,40%)]', items: [
          { id: 'wh1', text: '1x per week: Tackle one dedicated declutter session (1–2 hours)', checked: false },
          { id: 'wh2', text: '1x per week: List 3–5 new jewelry items for sale', checked: false },
          { id: 'wh3', text: 'Weekly: Check and respond to any buyer messages/offers on jewelry', checked: false },
          { id: 'wh4', text: 'Weekly: One donation bag out the door — don\'t let it pile up', checked: false },
        ]},
        { id: 'wa-health', title: '⚖️ Health', color: 'bg-[hsl(15,12%,37%)]', items: [
          { id: 'whh1', text: '3x per week: Dedicated movement session (walk, gym, class)', checked: false },
          { id: 'whh2', text: 'Sunday: Prep easy, healthy food for the week', checked: false },
          { id: 'whh3', text: 'Weekly: Review how your tracking went — any patterns to adjust?', checked: false },
          { id: 'whh4', text: 'End of each month: Weigh in and note your progress', checked: false },
        ]},
      ],
      webinarWeeks: [
        { id: 'wb1', label: 'Week of Mar 16', content: 'Finalize webinar topic + title. Create registration page. Send first announcement to your existing email list + announce on IG stories.', checked: false },
        { id: 'wb2', label: 'Week of Mar 23', content: 'Post 2x about the webinar on personal brand IG. DM 10–15 warm contacts personally inviting them. Share to Wildflower IG.', checked: false },
        { id: 'wb3', label: 'Week of Mar 30', content: 'Build out your webinar content (slides, talking points). Promote registration 3x this week.', checked: false },
        { id: 'wb4', label: 'Week of Apr 6', content: 'Webinar content finalized. Email registered attendees with a reminder. Push registration hard.', checked: false },
        { id: 'wb5', label: 'Week of Apr 13', content: 'Final push. Stories every day counting down. Send 2nd email reminder. Prep your closing offer: the $550 Social Media Audit.', checked: false },
        { id: 'wb6', label: 'Week of Apr 20 🎯', content: 'Run the webinar on April 22. Close with the $550 Audit offer. Follow up with every attendee within 24 hours. Goal: 3–5 audits sold.', isEvent: true, checked: false },
        { id: 'wb7', label: 'Week of Apr 27', content: 'Follow up with warm leads from webinar. Onboard any new clients. Repurpose webinar content into 3–5 posts.', checked: false },
      ],
      monthlyCheckpoints: [
        { id: 'mc-mar', header: 'End of March', items: [
          { id: 'mm1', text: 'Wildflower: Is 1 new management client signed or in final stages?', checked: false },
          { id: 'mm2', text: 'Wildflower: Is your lead pipeline documented somewhere?', checked: false },
          { id: 'mm3', text: 'Personal brand: Have you posted consistently this month?', checked: false },
          { id: 'mm4', text: 'Webinar: Is the registration page live and are you promoting it?', checked: false },
          { id: 'mm5', text: 'Home: Has debulking started? At least 2 rooms touched?', checked: false },
          { id: 'mm6', text: 'Jewelry: Are items listed on at least 2 platforms?', checked: false },
          { id: 'mm7', text: 'C&C: Is the store set up and products designed?', checked: false },
          { id: 'mm8', text: 'Redford: Are accounts created and posting has begun?', checked: false },
          { id: 'mm9', text: 'Health: Have you moved 3x/week? Down at least 2 lbs?', checked: false },
        ]},
        { id: 'mc-apr', header: 'End of April', items: [
          { id: 'ma1', text: 'Wildflower: 2 new management clients total signed?', checked: false },
          { id: 'ma2', text: 'Webinar: Ran on April 22 — how many attendees? Conversions?', checked: false },
          { id: 'ma3', text: 'Personal brand: Email list started? How many subscribers?', checked: false },
          { id: 'ma4', text: 'C&C: Store is live and first sales made?', checked: false },
          { id: 'ma5', text: 'Redford: Hitting 4–5 posts/week? Growing follower count?', checked: false },
          { id: 'ma6', text: 'Home: Is most furniture/clutter addressed? Jewelry selling?', checked: false },
          { id: 'ma7', text: 'Health: Down ~4 lbs total from start? (~154 lbs)', checked: false },
        ]},
        { id: 'mc-may', header: 'End of May', items: [
          { id: 'my1', text: 'Wildflower: 3 new management clients — Wildflower at ~$6,715/mo ex-CCBB?', checked: false },
          { id: 'my2', text: 'Personal brand: Posting consistently, list growing, first monetization in place?', checked: false },
          { id: 'my3', text: 'C&C: First regular sales — any products outperforming?', checked: false },
          { id: 'my4', text: 'Redford: 200+ followers, content rhythm solid, media kit drafted?', checked: false },
          { id: 'my5', text: 'Home: Fully decluttered. Jewelry mostly sold. Ready for the move?', checked: false },
          { id: 'my6', text: 'Health: ~152 lbs — 6 lbs down from March start?', checked: false },
          { id: 'my7', text: 'Overall: Do you feel less overwhelmed than March? You should.', checked: false },
        ]},
      ],
    },
    {
      id: 'phase2',
      number: 2,
      title: 'Close the Gap Before the Cliff',
      dates: 'June – August 2026 · ~3 months',
      focus: 'CCBB expires in ~3 months · Keep selling',
      colorClass: 'slate',
      countdownNote: 'CCBB drops off in September. By end of August, you need enough recurring Wildflower revenue to absorb that loss without feeling it.',
      intro: "This phase is about closing the gap before the CCBB cliff. You're also building the documented income history that qualifies you for a $220K home — with or without a cosigner. Every new client you sign and every W2 increase you take on record moves the mortgage needle. The income you build here is doing double duty.",
      actionGroups: [
        { id: 'p2-wf', icon: '🌸', title: 'Wildflower — Scale', items: [
          { id: 'p2w1', text: 'Monday: review GHL pipeline — who needs a follow-up this week?', type: 'urgent', checked: false, weekdayOnly: true },
          { id: 'p2w2', text: 'Send 1 referral ask to a current or past client ("Do you know anyone who needs social media help?")', type: 'normal', checked: false },
          { id: 'p2w3', text: 'Review content performance: what drove the most profile visits or inquiries this month?', type: 'normal', checked: false },
          { id: 'p2w4', text: 'Schedule a call with your accountant to officially increase your W2 salary on record', type: 'normal', checked: false, weekdayOnly: true },
          { id: 'p2w5', text: 'Save every bank statement and Wildflower invoice — document income growth month-over-month for the lender', type: 'normal', checked: false },
        ]},
        { id: 'p2-mort', icon: '🏡', title: 'Mortgage — $220K Home, 20% Down', items: [
          { id: 'p2m1', text: 'Research cosigner options — who in your life has strong credit and stable income?', type: 'urgent', checked: false },
          { id: 'p2m2', text: 'Once broker gives you a qualifying income target — track your W2 salary against it monthly', type: 'normal', checked: false },
          { id: 'p2m3', text: 'Write out must-haves vs. nice-to-haves for your home (do this once, keep it as your filter)', type: 'normal', checked: false },
          { id: 'p2m4', text: 'Browse listings 1x/week in the $175–225K range — stay current on the market', type: 'normal', checked: false },
          { id: 'p2m5', text: 'If W2 salary increase helps the application — make it official and document it as Wildflower revenue grows', type: 'normal', checked: false },
        ]},
        { id: 'p2-cc', icon: '☕', title: 'Coffee & Cavaliers — Phase 2', items: [
          { id: 'p2c1', text: 'Add new product variations based on what\'s selling — cut what isn\'t', type: 'normal', checked: false },
          { id: 'p2c2', text: 'Research and reach out to 1 micro-influencer collab or paid promotion this month', type: 'normal', checked: false },
          { id: 'p2c3', text: 'Check Etsy SEO monthly — are your listings showing up for the right searches?', type: 'normal', checked: false },
        ]},
        { id: 'p2-red', icon: '🐾', title: 'Redford — Scale UGC', items: [
          { id: 'p2r1', text: 'Send 3–5 brand outreach pitches this week (pet food, accessories, Cavalier products, coffee brands, lifestyle brands)', type: 'urgent', checked: false },
          { id: 'p2r2', text: 'Track all pitches in a simple spreadsheet: brand, date contacted, response, status', type: 'normal', checked: false },
          { id: 'p2r3', text: 'Update media kit with current follower count and engagement rate each month', type: 'normal', checked: false },
          { id: 'p2r4', text: 'Build rate card: price per UGC video, per static image, per story set (starting: $75–150/video, $50–100/static)', type: 'normal', checked: false },
        ]},
        { id: 'p2-pb', icon: '📱', title: 'Personal Brand — Phase 2', items: [
          { id: 'p2p1', text: 'Launch first monetized offer (digital product $27–47, affiliate partnership, or paid workshop $97–197)', type: 'money', checked: false },
          { id: 'p2p2', text: 'Promote offer in IG stories 1–2x this week', type: 'normal', checked: false },
          { id: 'p2p3', text: 'Send monthly value-led email to list — 1 soft CTA per email', type: 'normal', checked: false },
        ]},
        { id: 'p2-health', icon: '⚖️', title: 'Health — Phase 2', items: [
          { id: 'p2h1', text: 'If motivation has dipped: research and consider hiring a coach or accountability partner', type: 'normal', checked: false },
          { id: 'p2h2', text: 'Bump movement to 4x/week if energy supports it', type: 'normal', checked: false },
        ]},
      ],
      milestone: "Phase 2 milestone (end of August): Wildflower is at $9,000–9,500/mo without CCBB. Underwriting number received and home search active. Redford has paying brand deals. Personal brand earning first income. Weight: ~145 lbs. Down payment growing toward $35–50k target.",
    },
    {
      id: 'phase3',
      number: 3,
      title: 'Arrive',
      dates: 'September – December 2026 · ~4 months',
      focus: 'CCBB gone · You built past it',
      colorClass: 'olive',
      intro: "CCBB is gone — but you built past it. This phase is about hitting your financial targets, buying your home, and closing the year having genuinely transformed your life from the ground up.",
      actionGroups: [
        { id: 'p3-wf', icon: '🌸', title: 'Wildflower — Arrive', items: [
          { id: 'p3w1', text: 'Review GHL pipeline health: how many active prospects? How many stalled?', type: 'urgent', checked: false },
          { id: 'p3w2', text: 'Review your client roster — identify any service gaps or upsell opportunities', type: 'normal', checked: false },
          { id: 'p3w3', text: 'Document your client onboarding process so a new team member could run it', type: 'normal', checked: false },
        ]},
        { id: 'p3-home', icon: '🏡', title: 'Home — Buy a $220K Home', items: [
          { id: 'p3h1', text: 'Re-approach lender with updated income documentation (higher W2 + S-Corp growth)', type: 'urgent', checked: false },
          { id: 'p3h2', text: 'Work with a buyer\'s agent who knows your target market and price range', type: 'normal', checked: false },
          { id: 'p3h3', text: 'Make offers', type: 'normal', checked: false },
          { id: 'p3h4', text: 'Confirm $44K down payment is saved and cosigner (if needed) is in place — apply for pre-approval', type: 'urgent', checked: false },
          { id: 'p3h5', text: 'Complete all mortgage paperwork and closing requirements', type: 'normal', checked: false },
          { id: 'p3h6', text: 'Set up new home intentionally from day one — don\'t recreate the clutter', type: 'normal', checked: false },
        ]},
        { id: 'p3-cc', icon: '☕', title: 'Coffee & Cavaliers — Phase 3', items: [
          { id: 'p3c1', text: 'Design holiday product line by end of September', type: 'urgent', checked: false },
          { id: 'p3c2', text: 'Schedule holiday promotions: Black Friday, Cyber Monday, Christmas', type: 'normal', checked: false },
          { id: 'p3c3', text: 'Pitch C&C products to Cavalier-focused accounts and pet gift guide roundups', type: 'normal', checked: false },
        ]},
        { id: 'p3-red', icon: '🐾', title: 'Redford — Phase 3', items: [
          { id: 'p3r1', text: 'Pitch holiday gift guide placements to pet brands (September)', type: 'urgent', checked: false },
          { id: 'p3r2', text: 'Offer monthly UGC packages to convert one-off deals into recurring relationships', type: 'money', checked: false },
          { id: 'p3r3', text: 'Cross-promote C&C holiday products through Redford accounts', type: 'normal', checked: false },
        ]},
        { id: 'p3-pb', icon: '📱', title: 'Personal Brand — Phase 3', items: [
          { id: 'p3b1', text: 'Expand best-performing offer or create a higher-ticket version', type: 'money', checked: false },
          { id: 'p3b2', text: 'Launch consistent monthly email newsletter', type: 'normal', checked: false },
        ]},
        { id: 'p3-income', icon: '💰', title: 'Personal Income', items: [
          { id: 'p3i1', text: 'Schedule a meeting with your accountant to officially increase your W2 salary', type: 'urgent', checked: false },
          { id: 'p3i2', text: 'Talk to your CPA about setting up recurring S-Corp distributions', type: 'normal', checked: false },
          { id: 'p3i3', text: 'Review all income streams this month — note what\'s growing and what needs a push', type: 'normal', checked: false },
          { id: 'p3i4', text: 'Ask your CPA about optimizing your S-Corp compensation structure for 2027', type: 'normal', checked: false },
        ]},
        { id: 'p3-health', icon: '⚖️', title: 'Health — Phase 3', items: [
          { id: 'p3hl1', text: 'Shift 1 movement session per week toward strength training', type: 'normal', checked: false },
          { id: 'p3hl2', text: 'Start thinking about what "maintenance" looks like as a permanent lifestyle', type: 'normal', checked: false },
          { id: 'p3hl3', text: 'Celebrate your progress — note one thing you\'re proud of this month', type: 'normal', checked: false },
        ]},
      ],
      milestone: "Phase 3 milestone (end of December): Wildflower at $10k/month. You own a home. Personal take-home ~$10k/month post-tax. You weigh 135 lbs. Clean, organized home. Every goal achieved.",
    },
  ],
  weightGoal: {
    title: 'Health Goal: 158 → 135 lbs by December',
    body: 'Already down 2.7 lbs — you\'re moving. 20.3 lbs remaining over 9 months = about 2.3 lbs/month — a sustainable, healthy pace. The goal is a lifestyle shift, not a sprint.',
    milestones: ['Start: 158', 'Now: 155.3', 'Aug: ~143', 'Oct: ~139', 'Dec: 135 ✓'],
  },
  mindset: {
    title: 'A note for when it gets hard',
    body: "The CCBB deadline is real — but it's also a gift. It gives you a clear, unmovable reason to move with urgency right now. When it's hard to make that next sales call or post that next piece of content, remember: you're not grinding for a vague future goal. You're building the runway before September. That's concrete. That's motivating. Use the deadline.",
  },
  monthlyGoals: [
    { month: '2026-03-15', wildflowerRevenue: 2715, personalIGFollowers: 2633, wildflowerIGFollowers: 831, weight: 158, downPaymentSaved: 20000, emailSubscribers: 235, notes: 'Plan start — March 15, 2026. Currently at 155.3 lbs (down 2.7 from start). Loan not approved solo; cosigner needed. Target: $220K home, 20% down ($44K).' },
  ],
  weekendTasks: [
    { id: 'wknd-home1', text: 'Laundry — wash, dry, and put away (all the way)', category: 'Home Reset' },
    { id: 'wknd-home2', text: 'Clean the kitchen — wipe counters, stove, and sink', category: 'Home Reset' },
    { id: 'wknd-home3', text: 'Swiffer the floors', category: 'Home Reset' },
    { id: 'wknd-home4', text: 'Change the sheets', category: 'Home Reset' },
    { id: 'wknd-home5', text: 'Reset all drop zones — kitchen table, entryway, any piles', category: 'Home Reset' },
    { id: 'wknd-home6', text: 'Water the plants', category: 'Home Reset' },
    { id: 'wknd-decl1', text: '1–2 hour dedicated declutter session — pick one room or category', category: 'Declutter & Sell' },
    { id: 'wknd-decl2', text: 'List 3–5 jewelry items for sale', category: 'Declutter & Sell' },
    { id: 'wknd-decl3', text: 'One donation bag out the door', category: 'Declutter & Sell' },
    { id: 'wknd-fin1', text: 'Review bank account — anything unexpected?', category: 'Finance Check' },
    { id: 'wknd-fin2', text: 'Check credit card balance', category: 'Finance Check' },
    { id: 'wknd-fin3', text: 'Log down payment savings balance — still growing?', category: 'Finance Check' },
    { id: 'wknd-fin4', text: 'Check Wildflower invoices — any unpaid or overdue?', category: 'Finance Check' },
    { id: 'wknd-life1', text: 'Sunday meal prep — set yourself up so weekday food decisions are easy', category: 'Set Up for the Week' },
    { id: 'wknd-life2', text: 'Batch-plan content for the week — 3 feed posts + story topics', category: 'Set Up for the Week' },
    { id: 'wknd-life3', text: 'Get outside for a real walk — 20–30 minutes, no phone', category: 'Set Up for the Week' },
    { id: 'wknd-life4', text: 'Personal admin sweep — any messages sitting unanswered? Appointments to book?', category: 'Set Up for the Week' },
    { id: 'wknd-life5', text: 'One thing just for fun — no productivity attached', category: 'Set Up for the Week' },
  ],
  checkedItems: {},
  dashboard: {
    priorities: [],
    oneOffTasks: [],
    clientTasks: [],
    weightLog: [{ date: '2026-03-27', weight: 155.3 }],
    reflections: [],
    lastPriorityReset: '',
    lastUpdated: '',
    dailyResetDate: '',
    weeklyResetDate: '',
  },
};
